[env]
SHELL = "/opt/homebrew/bin/fish"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "--init-command", "tmux new-session -A -s main"]

[scrolling]
history = 0

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "none"
startup_mode = "Maximized"

[font]
normal = { family = "BigBlueTermPlus Nerd Font" }
size = 14.0
# normal = { family = "Iosevka Term", style = "Light" }
# bold = { style = "Semibold" }
# italic = { style = "Light Oblique" }
# size = 16.0

[colors.primary]
background = "#000000"
foreground = "#b9b9b9"

[keyboard]
bindings = [
    { key = "T", mods = "Command", chars = "\u0001c" },  # tmux: new window
    { key = "W", mods = "Command", chars = "\u0001x" },  # tmux: close window
    { key = "Z", mods = "Command", chars = "\u0001z" },  # tmux: zoom window
    { key = "P", mods = "Command", chars = "\u0001w" },  # tmux: switch window
    { key = "S", mods = "Command", chars = "\u001B:w\n" },  # nvim: write buffer
    { key = "D", mods = "Command", chars = "darkmode\n" },
]
