[general]
import = ["~/dotfiles/alacritty/.config/alacritty/alacritty.toml"]

[terminal.shell]
program = "fish"

[font]
normal = { family = "Iosevka Term Nerd Font", style = "Light" }
# normal = { family = "BigBlueTerm437 Nerd Font Mono" }
size = 14.0
