wtf:
  grid:
    columns: [80, 80, 80, 80]
    rows: [100]
  refreshInterval: 1
  mods:
    gcal:
      email: matteo@gorilla.co
      calendarReadLevel: reader
      displayResponseStatus: true
      timezone: Europe/Brussels
      hourFormat: '24'
      conflictIcon: '!'
      currentIcon: '*'
      eventCount: 32
      multiCalendar: false
      showDeclined: true
      showEndTime: true
      withLocation: true
      enabled: true
      refreshInterval: 5m
      secretFile: ~/.config/wtf/gcal/client_secret.json
      colors:
        title: white
        day: blue
        eventTime: cyan
        highlights:
        - ['1x1|1on1', green]
        past: gray
      position:
        top: 0
        left: 0
        height: 1
        width: 1
